### ISSUE TITLE
Documentation prospect

### ISSUE THREAD

**Issue by VarLad** [JuliaConstraints/CompositionalNetworks.jl#54]
Just an idea, and probably low priority at that.
I'm not sure that this is the best place to make the issue but,

I'd like JuliaConstraints to have a "combined" documentation. This new site would have docs of all the packages in JuliaConstraints.jl, as well as a basic tutorial for all of the packages. I champion https://github.com/lorenzoh/Pollen.jl/ to do this.
This would allow us to link different components of JuliaConstraints, as well as give us a chance to turn the documentation into something educational, as Pollen would allow us to write documents on very specific subtopics.
For reference on how Pollen looks like, refer to https://lorenzoh.github.io/Pollen.jl and https://fluxml.ai/FastAI.jl/dev/FastAI@dev/doc/README.md.html

**Comment by Azzaare** [comment]
Actually, this was the plan for a while. We have an almost empty repo https://github.com/JuliaConstraints/JuliaConstraints.github.io

As you can see, any contribution is likely to be an improvement! We can have a go for it with `Pollen.jl` if you feel like it.
